# Generated by Django 4.1.7 on 2023-04-05 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
